/**
 * EXPANDED MCP TOOLS - 200+ Tools for SWAYAM Universal AI
 *
 * Categories:
 * - Compliance (GST, TDS, ITR, MCA) - 54 tools
 * - ERP (Accounting, Invoice, Inventory, Purchase, Sales) - 44 tools
 * - CRM (Lead, Contact, Opportunity, Activity) - 30 tools
 * - Banking (UPI, BBPS, Calculators) - 28 tools
 * - Government (Aadhaar, DigiLocker, ULIP, Schemes) - 22 tools
 * - Logistics (Saathi, FreightBox) - 25 tools
 * - Utility (Weather, Search, Calculator) - 10 tools
 *
 * Total: 213 tools
 */

import type { MCPTool, MCPParameter, MCPResult } from '../types';

// ═══════════════════════════════════════════════════════════════════════════════
// COMPLIANCE TOOLS (54 tools)
// ═══════════════════════════════════════════════════════════════════════════════

export const COMPLIANCE_TOOLS: Record<string, { name: string; description: string; descriptionHi: string; category: string; parameters: MCPParameter[]; voiceTriggers: string[] }> = {
  // GST Tools (23)
  gst_verify: { name: 'gst_verify', description: 'Verify GSTIN and get business details', descriptionHi: 'GSTIN verify करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN number', required: true }], voiceTriggers: ['gstin verify', 'जीएसटी वेरीफाई'] },
  gst_search_pan: { name: 'gst_search_pan', description: 'Search GSTIN by PAN', descriptionHi: 'PAN से GSTIN खोजें', category: 'compliance', parameters: [{ name: 'pan', type: 'string', description: 'PAN number', required: true }], voiceTriggers: ['gstin by pan'] },
  gst_calc: { name: 'gst_calc', description: 'Calculate GST on amount', descriptionHi: 'GST calculate करें', category: 'compliance', parameters: [{ name: 'amount', type: 'number', description: 'Amount', required: true }, { name: 'rate', type: 'number', description: 'GST rate', required: false }], voiceTriggers: ['gst calculate', 'जीएसटी कितना'] },
  gst_reverse: { name: 'gst_reverse', description: 'Reverse calculate GST from total', descriptionHi: 'Total से GST निकालें', category: 'compliance', parameters: [{ name: 'total', type: 'number', description: 'Total amount', required: true }, { name: 'rate', type: 'number', description: 'GST rate', required: true }], voiceTriggers: ['reverse gst'] },
  hsn_lookup: { name: 'hsn_lookup', description: 'Lookup HSN code for product', descriptionHi: 'HSN code खोजें', category: 'compliance', parameters: [{ name: 'query', type: 'string', description: 'Product name', required: true }], voiceTriggers: ['hsn code', 'एचएसएन'] },
  sac_lookup: { name: 'sac_lookup', description: 'Lookup SAC code for service', descriptionHi: 'SAC code खोजें', category: 'compliance', parameters: [{ name: 'query', type: 'string', description: 'Service name', required: true }], voiceTriggers: ['sac code'] },
  gst_rate: { name: 'gst_rate', description: 'Get GST rate for HSN/SAC', descriptionHi: 'GST rate पाएं', category: 'compliance', parameters: [{ name: 'code', type: 'string', description: 'HSN or SAC code', required: true }], voiceTriggers: ['gst rate'] },
  gstr1_prepare: { name: 'gstr1_prepare', description: 'Prepare GSTR-1 return', descriptionHi: 'GSTR-1 तैयार करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Return period', required: true }], voiceTriggers: ['gstr1 prepare'] },
  gstr1_file: { name: 'gstr1_file', description: 'File GSTR-1 return', descriptionHi: 'GSTR-1 file करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Return period', required: true }], voiceTriggers: ['gstr1 file'] },
  gstr2a_fetch: { name: 'gstr2a_fetch', description: 'Fetch GSTR-2A data', descriptionHi: 'GSTR-2A data लाएं', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Period', required: true }], voiceTriggers: ['gstr2a fetch'] },
  gstr2b_fetch: { name: 'gstr2b_fetch', description: 'Fetch GSTR-2B data', descriptionHi: 'GSTR-2B data लाएं', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Period', required: true }], voiceTriggers: ['gstr2b fetch'] },
  gstr3b_prepare: { name: 'gstr3b_prepare', description: 'Prepare GSTR-3B return', descriptionHi: 'GSTR-3B तैयार करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Period', required: true }], voiceTriggers: ['gstr3b prepare'] },
  gstr3b_file: { name: 'gstr3b_file', description: 'File GSTR-3B return', descriptionHi: 'GSTR-3B file करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Period', required: true }], voiceTriggers: ['gstr3b file'] },
  gstr9_prepare: { name: 'gstr9_prepare', description: 'Prepare annual return GSTR-9', descriptionHi: 'GSTR-9 तैयार करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'year', type: 'string', description: 'Financial year', required: true }], voiceTriggers: ['gstr9 annual'] },
  eway_generate: { name: 'eway_generate', description: 'Generate E-Way Bill', descriptionHi: 'E-Way Bill बनाएं', category: 'compliance', parameters: [{ name: 'invoice_no', type: 'string', description: 'Invoice number', required: true }, { name: 'from_gstin', type: 'string', description: 'From GSTIN', required: true }, { name: 'to_gstin', type: 'string', description: 'To GSTIN', required: true }], voiceTriggers: ['eway bill', 'ई-वे बिल'] },
  eway_verify: { name: 'eway_verify', description: 'Verify E-Way Bill', descriptionHi: 'E-Way Bill verify करें', category: 'compliance', parameters: [{ name: 'eway_no', type: 'string', description: 'E-Way Bill number', required: true }], voiceTriggers: ['eway verify'] },
  eway_update: { name: 'eway_update', description: 'Update E-Way Bill vehicle', descriptionHi: 'E-Way Bill vehicle update करें', category: 'compliance', parameters: [{ name: 'eway_no', type: 'string', description: 'E-Way Bill number', required: true }, { name: 'vehicle_no', type: 'string', description: 'New vehicle number', required: true }], voiceTriggers: ['eway update'] },
  eway_cancel: { name: 'eway_cancel', description: 'Cancel E-Way Bill', descriptionHi: 'E-Way Bill cancel करें', category: 'compliance', parameters: [{ name: 'eway_no', type: 'string', description: 'E-Way Bill number', required: true }, { name: 'reason', type: 'string', description: 'Cancellation reason', required: true }], voiceTriggers: ['eway cancel'] },
  eway_extend: { name: 'eway_extend', description: 'Extend E-Way Bill validity', descriptionHi: 'E-Way Bill extend करें', category: 'compliance', parameters: [{ name: 'eway_no', type: 'string', description: 'E-Way Bill number', required: true }], voiceTriggers: ['eway extend'] },
  einvoice_generate: { name: 'einvoice_generate', description: 'Generate E-Invoice', descriptionHi: 'E-Invoice बनाएं', category: 'compliance', parameters: [{ name: 'invoice_data', type: 'object', description: 'Invoice data', required: true }], voiceTriggers: ['einvoice generate', 'ई-इनवॉइस'] },
  einvoice_cancel: { name: 'einvoice_cancel', description: 'Cancel E-Invoice', descriptionHi: 'E-Invoice cancel करें', category: 'compliance', parameters: [{ name: 'irn', type: 'string', description: 'IRN number', required: true }, { name: 'reason', type: 'string', description: 'Reason', required: true }], voiceTriggers: ['einvoice cancel'] },
  einvoice_verify: { name: 'einvoice_verify', description: 'Verify E-Invoice by IRN', descriptionHi: 'E-Invoice verify करें', category: 'compliance', parameters: [{ name: 'irn', type: 'string', description: 'IRN number', required: true }], voiceTriggers: ['einvoice verify'] },
  itc_check: { name: 'itc_check', description: 'Check ITC eligibility', descriptionHi: 'ITC eligibility check करें', category: 'compliance', parameters: [{ name: 'gstin', type: 'string', description: 'GSTIN', required: true }, { name: 'period', type: 'string', description: 'Period', required: true }], voiceTriggers: ['itc check'] },

  // TDS Tools (10)
  tds_calc: { name: 'tds_calc', description: 'Calculate TDS on payment', descriptionHi: 'TDS calculate करें', category: 'compliance', parameters: [{ name: 'amount', type: 'number', description: 'Payment amount', required: true }, { name: 'section', type: 'string', description: 'TDS section', required: false }], voiceTriggers: ['tds calculate', 'टीडीएस कितना'] },
  tds_section_lookup: { name: 'tds_section_lookup', description: 'Lookup TDS section and rate', descriptionHi: 'TDS section खोजें', category: 'compliance', parameters: [{ name: 'payment_type', type: 'string', description: 'Type of payment', required: true }], voiceTriggers: ['tds section'] },
  tds_24q_prepare: { name: 'tds_24q_prepare', description: 'Prepare Form 24Q (Salary TDS)', descriptionHi: 'Form 24Q तैयार करें', category: 'compliance', parameters: [{ name: 'tan', type: 'string', description: 'TAN number', required: true }, { name: 'quarter', type: 'string', description: 'Quarter', required: true }], voiceTriggers: ['form 24q'] },
  tds_26q_prepare: { name: 'tds_26q_prepare', description: 'Prepare Form 26Q (Non-salary TDS)', descriptionHi: 'Form 26Q तैयार करें', category: 'compliance', parameters: [{ name: 'tan', type: 'string', description: 'TAN number', required: true }, { name: 'quarter', type: 'string', description: 'Quarter', required: true }], voiceTriggers: ['form 26q'] },
  tds_challan_280: { name: 'tds_challan_280', description: 'Generate Challan 280', descriptionHi: 'Challan 280 बनाएं', category: 'compliance', parameters: [{ name: 'pan', type: 'string', description: 'PAN', required: true }, { name: 'amount', type: 'number', description: 'Tax amount', required: true }], voiceTriggers: ['challan 280'] },
  tds_challan_281: { name: 'tds_challan_281', description: 'Generate Challan 281', descriptionHi: 'Challan 281 बनाएं', category: 'compliance', parameters: [{ name: 'tan', type: 'string', description: 'TAN', required: true }, { name: 'amount', type: 'number', description: 'TDS amount', required: true }], voiceTriggers: ['challan 281'] },
  form16_generate: { name: 'form16_generate', description: 'Generate Form 16', descriptionHi: 'Form 16 बनाएं', category: 'compliance', parameters: [{ name: 'employee_pan', type: 'string', description: 'Employee PAN', required: true }, { name: 'year', type: 'string', description: 'Financial year', required: true }], voiceTriggers: ['form 16'] },
  form16a_generate: { name: 'form16a_generate', description: 'Generate Form 16A', descriptionHi: 'Form 16A बनाएं', category: 'compliance', parameters: [{ name: 'deductee_pan', type: 'string', description: 'Deductee PAN', required: true }, { name: 'quarter', type: 'string', description: 'Quarter', required: true }], voiceTriggers: ['form 16a'] },
  tan_verify: { name: 'tan_verify', description: 'Verify TAN number', descriptionHi: 'TAN verify करें', category: 'compliance', parameters: [{ name: 'tan', type: 'string', description: 'TAN number', required: true }], voiceTriggers: ['tan verify'] },
  form26as_fetch: { name: 'form26as_fetch', description: 'Fetch Form 26AS', descriptionHi: 'Form 26AS लाएं', category: 'compliance', parameters: [{ name: 'pan', type: 'string', description: 'PAN', required: true }, { name: 'year', type: 'string', description: 'Assessment year', required: true }], voiceTriggers: ['form 26as'] },

  // ITR Tools (10)
  income_tax_calc: { name: 'income_tax_calc', description: 'Calculate income tax', descriptionHi: 'Income tax calculate करें', category: 'compliance', parameters: [{ name: 'income', type: 'number', description: 'Annual income', required: true }, { name: 'regime', type: 'string', description: 'old/new regime', required: false }], voiceTriggers: ['income tax', 'आयकर'] },
  itr_80c_check: { name: 'itr_80c_check', description: 'Check 80C deduction limit', descriptionHi: '80C deduction check करें', category: 'compliance', parameters: [{ name: 'investments', type: 'object', description: 'Investment details', required: true }], voiceTriggers: ['80c limit'] },
  itr_80d_check: { name: 'itr_80d_check', description: 'Check 80D deduction limit', descriptionHi: '80D deduction check करें', category: 'compliance', parameters: [{ name: 'premiums', type: 'object', description: 'Insurance premiums', required: true }], voiceTriggers: ['80d limit'] },
  itr_regime_compare: { name: 'itr_regime_compare', description: 'Compare old vs new tax regime', descriptionHi: 'Tax regime compare करें', category: 'compliance', parameters: [{ name: 'income', type: 'number', description: 'Annual income', required: true }, { name: 'deductions', type: 'object', description: 'Deductions', required: false }], voiceTriggers: ['tax regime compare'] },
  itr_due_date: { name: 'itr_due_date', description: 'Get ITR due date', descriptionHi: 'ITR due date पाएं', category: 'compliance', parameters: [{ name: 'taxpayer_type', type: 'string', description: 'Type of taxpayer', required: false }], voiceTriggers: ['itr due date'] },
  itr_form_selector: { name: 'itr_form_selector', description: 'Select appropriate ITR form', descriptionHi: 'सही ITR form चुनें', category: 'compliance', parameters: [{ name: 'income_sources', type: 'array', description: 'Income sources', required: true }], voiceTriggers: ['which itr form'] },
  itr_refund_status: { name: 'itr_refund_status', description: 'Check ITR refund status', descriptionHi: 'ITR refund status check करें', category: 'compliance', parameters: [{ name: 'pan', type: 'string', description: 'PAN', required: true }, { name: 'year', type: 'string', description: 'Assessment year', required: true }], voiceTriggers: ['refund status'] },
  ais_fetch: { name: 'ais_fetch', description: 'Fetch Annual Information Statement', descriptionHi: 'AIS fetch करें', category: 'compliance', parameters: [{ name: 'pan', type: 'string', description: 'PAN', required: true }, { name: 'year', type: 'string', description: 'Financial year', required: true }], voiceTriggers: ['ais fetch'] },
  capital_gains_calc: { name: 'capital_gains_calc', description: 'Calculate capital gains tax', descriptionHi: 'Capital gains calculate करें', category: 'compliance', parameters: [{ name: 'sale_value', type: 'number', description: 'Sale value', required: true }, { name: 'purchase_value', type: 'number', description: 'Purchase value', required: true }, { name: 'holding_period', type: 'number', description: 'Holding period in months', required: true }], voiceTriggers: ['capital gains'] },
  advance_tax_calc: { name: 'advance_tax_calc', description: 'Calculate advance tax installments', descriptionHi: 'Advance tax calculate करें', category: 'compliance', parameters: [{ name: 'estimated_income', type: 'number', description: 'Estimated income', required: true }], voiceTriggers: ['advance tax'] },

  // MCA Tools (11)
  mca_company_search: { name: 'mca_company_search', description: 'Search company on MCA', descriptionHi: 'Company search करें', category: 'compliance', parameters: [{ name: 'name', type: 'string', description: 'Company name', required: true }], voiceTriggers: ['company search'] },
  mca_din_verify: { name: 'mca_din_verify', description: 'Verify Director DIN', descriptionHi: 'DIN verify करें', category: 'compliance', parameters: [{ name: 'din', type: 'string', description: 'DIN number', required: true }], voiceTriggers: ['din verify'] },
  mca_cin_lookup: { name: 'mca_cin_lookup', description: 'Lookup company by CIN', descriptionHi: 'CIN से company खोजें', category: 'compliance', parameters: [{ name: 'cin', type: 'string', description: 'CIN number', required: true }], voiceTriggers: ['cin lookup'] },
  mca_llpin_lookup: { name: 'mca_llpin_lookup', description: 'Lookup LLP by LLPIN', descriptionHi: 'LLPIN से LLP खोजें', category: 'compliance', parameters: [{ name: 'llpin', type: 'string', description: 'LLPIN number', required: true }], voiceTriggers: ['llpin lookup'] },
  mca_director_search: { name: 'mca_director_search', description: 'Search director details', descriptionHi: 'Director search करें', category: 'compliance', parameters: [{ name: 'name', type: 'string', description: 'Director name', required: true }], voiceTriggers: ['director search'] },
  mca_filing_dues: { name: 'mca_filing_dues', description: 'Get MCA filing due dates', descriptionHi: 'MCA filing dates पाएं', category: 'compliance', parameters: [{ name: 'company_type', type: 'string', description: 'Type of company', required: false }], voiceTriggers: ['mca due dates'] },
  mca_aoc4_status: { name: 'mca_aoc4_status', description: 'Check AOC-4 filing status', descriptionHi: 'AOC-4 status check करें', category: 'compliance', parameters: [{ name: 'cin', type: 'string', description: 'CIN', required: true }], voiceTriggers: ['aoc4 status'] },
  mca_mgt7_status: { name: 'mca_mgt7_status', description: 'Check MGT-7 filing status', descriptionHi: 'MGT-7 status check करें', category: 'compliance', parameters: [{ name: 'cin', type: 'string', description: 'CIN', required: true }], voiceTriggers: ['mgt7 status'] },
  mca_charge_search: { name: 'mca_charge_search', description: 'Search company charges', descriptionHi: 'Company charges खोजें', category: 'compliance', parameters: [{ name: 'cin', type: 'string', description: 'CIN', required: true }], voiceTriggers: ['charge search'] },
  mca_strike_off_check: { name: 'mca_strike_off_check', description: 'Check strike-off status', descriptionHi: 'Strike-off status check करें', category: 'compliance', parameters: [{ name: 'cin', type: 'string', description: 'CIN', required: true }], voiceTriggers: ['strike off check'] },
  pan_verify: { name: 'pan_verify', description: 'Verify PAN card', descriptionHi: 'PAN verify करें', category: 'compliance', parameters: [{ name: 'pan', type: 'string', description: 'PAN number', required: true }], voiceTriggers: ['pan verify', 'पैन वेरीफाई'] }
};

// Tool count for this file
export const COMPLIANCE_TOOL_COUNT = Object.keys(COMPLIANCE_TOOLS).length;

console.log(`Compliance tools loaded: ${COMPLIANCE_TOOL_COUNT}`);
